# Generated by Django 3.0.2 on 2020-01-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=19)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('login_streak', models.IntegerField(default=0)),
                ('puzzle_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=200)),
                ('token_count', models.IntegerField(default=0)),
                ('token_ac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
