# Generated by Django 3.0.2 on 2020-01-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_type',
        ),
        migrations.AddField(
            model_name='token',
            name='puzzle_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='puzzle_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='puzzle_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='puzzle_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='puzzle_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
    ]
