# Generated by Django 3.0.2 on 2020-01-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200131_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token_ac_id',
            new_name='ac_id',
        ),
    ]
